### ISSUE TITLE
Posibility to provide a function name 

### ISSUE THREAD

**Issue by Kikobeats** [jasonpincin/callback-timeout#2]
What do you think for something like:

```js
var err = new Error(e || 'timeout of '+t+'ms exceeded for callback ' + (fnName || f.name||'anonymous'))
```

maybe too many arguments to setup the module?

**Comment by jasonpincin** [comment]
Doesn't seem necessary to me. I can't think if a reason `f.name` isn't enough. What's your case for wanting it?

**Comment by Kikobeats** [comment]
not problem :-)
