### ISSUE TITLE
Custom Error

### ISSUE THREAD

**Issue by Kikobeats** [jasonpincin/callback-timeout#3]
Using this library I have to do the follow error wrapper:

```
if (err && err.name === 'TimeoutError') err = {code: 'ETIMEDOUT'}
```

Could be possible specify how to create the error and provide your factory as default?

**Comment by jasonpincin** [comment]
You have access to the error constructor via:

```javascript
var TimeoutError = require('callback-timeout/errors').TimeoutError

var err = new TimeoutError('timed out')
if (err instanceof TimeoutError) { /* ... */ }
```

Does this address your need?

**Comment by jasonpincin** [comment]
If on the other hand you want to customize the TimeoutError that gets thrown with your error code we could make that possible with a trivial change.

**Comment by Kikobeats** [comment]
but modify the constructor of the library is a bit weird. Something like provide a param could be enough

**Comment by jasonpincin** [comment]
How do you propose this would look? Have a code sample that shows providing the custom error factory?

**Comment by Kikobeats** [comment]
I'm going to create a PR
