### ISSUE TITLE
Why do you need to clear timeout when the timeout is called?

### ISSUE THREAD

**Issue by soichih** [jasonpincin/callback-timeout#7]
I am trying to study this code, and I can't quite understand why this line exists.

> https://github.com/jasonpincin/callback-timeout/blob/601df932f7c7c58025335fac661de3188c67ad43/index.js#L9

Can you explain why this line needs to exist?

**Comment by jasonpincin** [comment]
Good catch; you're correct, it does not need to exist.

**Comment by jasonpincin** [comment]
Removed that unnecessary statement and published `3.0.1`. Thanks for opening the issue!
